include: "rules/samples_tsv_functions.smk"
include: "rules/fastqc.smk"
include: "rules/samtools.smk"


rule test:
    input:
        rules.test_fastqc.input,
        rules.test_samtools_bam.input,
        rules.test_samtools_fa.input,
