# pre-commit hooks
---
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.5.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.2
    hooks:
      - id: snakefmt
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  # - repo: https://github.com/lorenzwalthert/precommit
  #   rev: v0.3.2
  #   hooks:
  #     - id: style-files
  #       additional_dependencies:
  #         - r-lib/styler
  #     - id: lintr
  #       additional_dependencies:
  #         - r-lib/lintr
