# Run tests over snakefile workflow
---
name: Tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

env:
  CACHE_NUMBER: 0  # Increment this number to invalidate the cache

jobs:

  Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Pre-Commit
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up caches
        uses: actions/cache@v4
        with:
          path: |
            .snakemake/conda
            ~/.cache/pre-commit/
          key: snakemake-conda-${{ env.CACHE_NUMBER }}

      - name: Clean conda cache
        run: conda clean --all --yes

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >
            --use-conda
            --show-failed-logs
            --cores 3
            --conda-cleanup-pkgs cache
            --latency-wait 10
            preprocess__multiqc__all

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: results
          path: |
            results/**/*.log
            # results/
            # reports/
            # !**/*.cram
            # !**/*.fq.gz
            # !**/*.bam
            # !**/*.bt2
